### ISSUE TITLE
[Meilisearch] Multi Index Search support

### ISSUE THREAD

**Issue by alexander-schranz** [schranz-search/schranz-search#28]
Currently Meilisearch does not support searching in multiple indexes and will throw instead a RuntimeException:

https://github.com/schranz-search/schranz-search/blob/373389a4e28be2964ed64c646096528246f0d6dc/packages/seal-meilisearch-adapter/MeilisearchConnection.php#L74-L76

External Issue: https://github.com/meilisearch/product/discussions/489#discussioncomment-4587143

**Comment by ToshY** [comment]
Saw your mention in #99. Since [`v1.10.0`](https://github.com/meilisearch/meilisearch/releases/tag/v1.10.0) Meilisearch supports "federated search", which can be used to search across multiple indexes in a single query: https://www.meilisearch.com/docs/reference/api/multi_search#federated-multi-search

**Comment by alexander-schranz** [comment]
I'm aware of that, the first federated search was just same query on multiple index and a result per index. Nothing which couldnt workaround with raw PHP itself. But even if the aggregated result isnt longer experimental the other engines will not move forward with it.

**Comment by alexander-schranz** [comment]
at current state we will not implement multi index search see #99 and #451
